baseURL = "https://hasmyssnbeenpwned.com/"
languageCode = "en-us"
title = "Has my SSN been pwned?"

theme = "reveal-hugo"

[params.reveal_hugo]
theme = "sky"
reveal_cdn = "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0"
highlight_cdn = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
